Custom BPP
YuliaShvets/parking-rest-api pull request #3
Opened 2023-08-29 13:47 UTC by YuliaShvets

2023-08-29 14:47 UTC, ajax-gnatiuk-s commented
@Wectro20 review please

2023-08-29 14:49 UTC, ajax-gnatiuk-s commented
You have mixed two independent features in the single PR:
- migration to gradle
- BPP

Please, split into two separate PRs.

2023-08-29 14:49 UTC, ajax-gnatiuk-s requested changes
You have mixed two independent features in the single PR:
- migration to gradle
- BPP

Please, split into two separate PRs.

2023-08-30 08:49 UTC, Wectro20 commented on src/main/java/ua/lviv/iot/parkingServer/config/TrackMetricsBeanPostProcessor.kt
> +                    println("Memory usage change: ${memoryAfter - memoryBefore} bytes.")
Instead of using println for logging, consider using a proper logging framework

2023-08-30 08:49 UTC, Wectro20 commented on src/main/java/ua/lviv/iot/parkingServer/config/TrackMetricsBeanPostProcessor.kt
> +            )
Single Responsibility: move the proxy creation logic to a separate private function for better code organization.

2023-08-30 08:49 UTC, Wectro20 commented on src/main/java/ua/lviv/iot/parkingServer/controller/ParkingController.kt
> +    fun deleteParking(@PathVariable parkingId: Long): Parking? = parkingService.deleteEntity(parkingId)
remove nullable type

2023-08-30 08:49 UTC, Wectro20 commented on src/main/java/ua/lviv/iot/parkingServer/logic/services/interfaces/ParkingSpotServiceInterface.kt
> +}
Remove brackets because your interface has empty body.
Add newline at the end of file

2023-08-30 08:49 UTC, Wectro20 commented on src/main/java/ua/lviv/iot/parkingServer/logic/services/interfaces/GeneralServiceInterface.kt
> +
remove redundant space
add newline at the end of the file

2023-08-30 08:49 UTC, Wectro20 commented on src/main/java/ua/lviv/iot/parkingServer/logic/services/interfaces/ParkingServiceInterface.kt
> +}
Remove brackets because your interface has empty body. Add newline at the end of file

2023-08-30 08:49 UTC, Wectro20 commented on src/main/java/ua/lviv/iot/parkingServer/logic/services/interfaces/VehicleServiceInterface.kt
> +}
Remove brackets because your interface has empty body. Add newline at the end of file

2023-08-30 08:49 UTC, Wectro20 commented on src/main/java/ua/lviv/iot/parkingServer/logic/VehicleService.kt
>  }
add newline at the end of the file

2023-08-30 14:27 UTC, merged